# Generated by Django 4.2.2 on 2026-04-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_base_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='base_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_stops_per_route',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
