# Generated by Django 4.2.2 on 2023-07-08 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodo',
            old_name='cuadrante',
            new_name='quadrant',
        ),
        migrations.AlterField(
            model_name='nodo',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relational_nodos', to='RMapp.origin'),
        ),
    ]
