# Generated by Django 4.2.2 on 2023-07-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMapp', '0002_rename_cuadrante_nodo_quadrant_alter_nodo_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodo',
            name='quadrant',
            field=models.CharField(max_length=3),
        ),
    ]
