# Generated by Django 4.2.2 on 2023-07-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMapp', '0005_nodo_origin_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodo',
            name='origin_distance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
    ]
