# Generated by Django 4.2.2 on 2026-04-26 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('RMapp', '0006_alter_nodo_origin_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='accounts.organization'),
        ),
    ]
