# Generated by Django 4.2.2 on 2026-04-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_base_lat_and_more'),
        ('RMapp', '0007_origin_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('place_kind', models.CharField(choices=[('origin', 'Origin'), ('destination', 'Destination')], default='destination', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to='accounts.organization')),
            ],
            options={
                'ordering': ['-is_favorite', '-usage_count', '-last_used_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='savedplace',
            constraint=models.UniqueConstraint(fields=('organization', 'address', 'place_kind'), name='unique_saved_place_per_org_and_kind'),
        ),
    ]
