"""
Django settings for Route_Maker project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

from .env import load_env_file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_env_file(BASE_DIR.parent / '.env')


def get_bool_env(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY is not configured.')

GEOAPIFY_API_KEY = os.getenv('GEOAPIFY_API_KEY', '')
GEOAPIFY_AUTOCOMPLETE_LANG = os.getenv('GEOAPIFY_AUTOCOMPLETE_LANG', 'es')
GEOAPIFY_AUTOCOMPLETE_COUNTRY_BIAS = os.getenv('GEOAPIFY_AUTOCOMPLETE_COUNTRY_BIAS', 'pe')
GEOAPIFY_AUTOCOMPLETE_COUNTRY_FILTER = os.getenv('GEOAPIFY_AUTOCOMPLETE_COUNTRY_FILTER', '')
GEOAPIFY_AUTOCOMPLETE_LANG = os.getenv('GEOAPIFY_AUTOCOMPLETE_LANG', 'es')
GEOAPIFY_AUTOCOMPLETE_COUNTRY_BIAS = os.getenv('GEOAPIFY_AUTOCOMPLETE_COUNTRY_BIAS', 'pe')
GEOAPIFY_AUTOCOMPLETE_COUNTRY_FILTER = os.getenv('GEOAPIFY_AUTOCOMPLETE_COUNTRY_FILTER', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool_env('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = [
    host.strip() for host in os.getenv(
        'DJANGO_ALLOWED_HOSTS',
        '127.0.0.1,localhost,testserver,BryntPN.pythonanywhere.com',
    ).split(',') if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'accounts.apps.AccountsConfig',
    'RMapp.apps.RmappConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Route_Maker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Route_Maker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.getenv('POSTGRES_DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB_NAME'),
            'USER': os.getenv('POSTGRES_DB_USER', ''),
            'PASSWORD': os.getenv('POSTGRES_DB_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_DB_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.getenv('SQLITE_DB_NAME', 'db.local.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'RMapp:index'
LOGOUT_REDIRECT_URL = 'accounts:login'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
